import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
    en: {
        nav: {
            home: 'Home',
            about: 'About',
            howToUse: 'How to Use',
            download: 'Download',
            downloadNow: 'Download Now',
        },
        hero: {
            version: 'Version 1.0 Available Now',
            title: 'Your Personal',
            titleHighlight: 'Cloud Storage',
            description: 'Store, sync, and access your files from anywhere. HomeCloud transforms your PC into a powerful personal cloud server.',
            downloadFree: 'Download Free',
            learnMore: 'Learn More',
            appPreview: 'App Preview',
        },
        features: {
            title: 'Powerful Features',
            description: 'Everything you need to manage your personal cloud storage efficiently and securely.',
            secureStorage: 'Secure Storage',
            secureStorageDesc: 'Your files are stored securely on your own server with end-to-end encryption.',
            multiPlatform: 'Multi-Platform',
            multiPlatformDesc: 'Access your files from Android, iOS, Windows, or Linux.',
            autoSync: 'Auto Sync',
            autoSyncDesc: 'Automatically backup and sync your photos, videos, and documents.',
            fastReliable: 'Fast & Reliable',
            fastReliableDesc: 'Lightning-fast uploads and downloads with reliable server performance.',
            serverMonitoring: 'Server Monitoring',
            serverMonitoringDesc: 'Real-time monitoring of CPU, RAM, storage, and network usage.',
            freeOpen: 'Free & Open',
            freeOpenDesc: 'No monthly fees. Host on your own hardware and maintain full control.',
        },
        platforms: {
            title: 'Available Everywhere',
            description: 'Access your files from any device, anywhere in the world.',
        },
        cta: {
            title: 'Ready to Get Started?',
            description: 'Download HomeCloud now and start managing your personal cloud storage for free.',
            button: 'Download Now',
        },
        howToUse: {
            title: 'How to Use',
            subtitle: 'Complete guide to install and connect HomeCloud app with your server.',
            featuresTitle: '✨ Available Features',
            featuresDesc: 'HomeCloud comes with powerful features to manage your personal cloud storage.',
            uploadDownload: 'Upload & Download',
            uploadDownloadDesc: 'Upload files or folders from your device, and download anytime easily.',
            autoBackup: 'Auto Backup',
            autoBackupDesc: 'Automatically backup photos and videos from your phone gallery to the server.',
            fileManager: 'File Manager',
            fileManagerDesc: 'Manage files easily: rename, move, delete, and create new folders.',
            mediaPlayer: 'Media Player',
            mediaPlayerDesc: 'Play videos and music directly from the app with streaming from server.',
            secureAccess: 'Secure Access',
            secureAccessDesc: 'Secure access with user authentication and data encryption.',
            step1: 'STEP 1',
            step2: 'STEP 2',
            step3: 'STEP 3',
            serverSetup: '🖥️ Setup Backend Server',
            serverSetupDesc: 'This server is the center of your data storage. Install on a PC that is always on.',
            clientSetup: '📱 Install Client App',
            clientSetupDesc: 'App to access and manage your files from various devices.',
            connectionGuide: '🔗 Connect App to Server',
            ensureServerOn: 'Ensure Server is On',
            ensureServerOnDesc: 'Run backend server on your computer with command',
            findIp: 'Find Server IP Address',
            findIpDescWindows: 'Windows: Open CMD, type',
            findIpDescLinux: 'Linux: Open Terminal, type',
            enterAddress: 'Enter Address into App',
            enterAddressDesc: 'Format:',
            enterAddressExample: 'Example:',
            done: 'Done!',
            doneDesc: 'Login with your account and start managing your personal cloud files.',
            serverRequirements: '📋 Server Requirements',
            tips: '💡 Important Tips',
            tipRemote: 'Access from Outside Network',
            tipRemoteDesc: 'To access server from outside home, configure Port Forwarding on your router or use services like Ngrok/Tailscale.',
            tipSecurity: 'Security',
            tipSecurityDesc: 'Ensure your account password is strong and consider enabling HTTPS if server is accessed publicly.',
            tipBackup: 'Data Backup',
            tipBackupDesc: 'Always make periodic backups of your server data to prevent data loss.',
            tipAlwaysOn: 'Server Always On',
            tipAlwaysOnDesc: 'Use a computer/laptop that is always on or use a VPS/cloud server for 24/7 availability.',
            serverSteps: [
                { title: 'Install Golang', description: 'Ensure Go (Golang) is installed on your system. Download from go.dev if not.' },
                { title: 'Download Server', description: 'Download HomeCloud Server source code (.zip) from Download page.' },
                { title: 'Extract File', description: 'Extract the .zip file to a folder of your choice on your computer/server.' },
                { title: 'Run Server', description: 'Open terminal in that folder and run: go run main.go. Server will be active on default port.' },
            ],
            appSteps: [
                { title: 'Download App', description: 'Choose your platform (Android/Windows/Linux) and download the app.' },
                { title: 'Install App', description: 'Install APK file (Android), EXE (Windows), or AppImage (Linux).' },
                { title: 'Enter Server Address', description: 'Open app, enter your server IP and Port (example: http://192.168.1.10:8080).' },
                { title: 'Login & Use', description: 'Login with your account and start managing your cloud files!' },
            ]
        },
        download: {
            title: 'Download',
            subtitle: 'Choose your platform and start using your personal cloud storage today. All downloads are free.',
            clientApps: 'Client Applications',
            serverApp: 'Server Application',
            serverAppDesc: 'Install this on your PC or server to host your cloud storage.',
            systemReq: 'System Requirements',
            mobileApps: 'Mobile Apps',
            desktopServer: 'Desktop & Server',
            comingSoon: 'Coming Soon',
            openApp: 'Open App',
            download: 'Download',
            serverDownload: {
                name: 'HomeCloud Server Source',
                desc: 'Backend server source code (Requires Golang)',
            },
            reqMobile: [
                '• Android 7.0 (Nougat) or later',
                '• iOS 12.0 or later',
                '• At least 100 MB free storage',
                '• Internet connection'
            ],
            reqServer: [
                '• Windows, Linux, or macOS',
                '• Go (Golang) 1.18 or later installed',
                '• 2 GB RAM minimum',
                '• 500 MB free storage (plus your files)',
                '• Network access for remote connections'
            ]
        },
        about: {
            title: 'About',
            subtitle: 'HomeCloud is a self-hosted cloud storage solution that gives you full control over your data.',
            whatIsTitle: 'What is HomeCloud?',
            whatIsDesc1: 'HomeCloud is your personal data sanctuary. Unlike public cloud services, your data stays on your own device.',
            whatIsDesc2: 'We built HomeCloud to give you the convenience of cloud storage without complying with third-party privacy policies.',
            whatIsDesc3: 'Complete control, zero subscription fees, and unlimited storage potential.',
            statsPrivate: 'Private',
            statsFee: 'Fees',
            statsPlatforms: 'Platforms',
            statsStorage: 'Storage',
            howItWorksTitle: 'How It Works',
            howItWorksDesc: 'Getting started with HomeCloud is simple. Set up your server, connect your devices, and start syncing.',
            step1Title: 'Set Up Server',
            step1Desc: 'Install the backend on your PC or always-on device.',
            step2Title: 'Connect App',
            step2Desc: 'Download the client app and enter your server IP.',
            step3Title: 'Start Syncing',
            step3Desc: 'Upload files and access them from anywhere.',
            missionTitle: 'Our Mission',
            missionDesc: 'To provide a secure, private, and easy-to-use cloud storage alternative that respects your privacy and data ownership.',
            storyTitle: 'Our Story',
            storyDesc: 'Started as a personal project to solve the issue of limited storage on free cloud services, HomeCloud has evolved into a robust platform for everyone.',
            teamTitle: 'The Team',
            teamDesc: 'Built by passionate developers who believe in the future of decentralized and self-hosted software.',
        }
    },
    id: {
        nav: {
            home: 'Beranda',
            about: 'Tentang',
            howToUse: 'Cara Pakai',
            download: 'Unduh',
            downloadNow: 'Unduh Sekarang',
        },
        hero: {
            version: 'Versi 1.0 Tersedia Sekarang',
            title: 'Penyimpanan Awan',
            titleHighlight: 'Pribadi Anda',
            description: 'Simpan, sinkronkan, dan akses file Anda dari mana saja. HomeCloud mengubah PC Anda menjadi server cloud pribadi yang andal.',
            downloadFree: 'Unduh Gratis',
            learnMore: 'Pelajari Lebih Lanjut',
            appPreview: 'Pratinjau Aplikasi',
        },
        features: {
            title: 'Fitur Canggih',
            description: 'Segala yang Anda butuhkan untuk mengelola penyimpanan cloud pribadi Anda secara efisien dan aman.',
            secureStorage: 'Penyimpanan Aman',
            secureStorageDesc: 'File Anda disimpan dengan aman di server Anda sendiri dengan enkripsi end-to-end.',
            multiPlatform: 'Multi-Platform',
            multiPlatformDesc: 'Akses file Anda dari Android, iOS, Windows, atau Linux.',
            autoSync: 'Sinkronisasi Otomatis',
            autoSyncDesc: 'Backup dan sinkronkan foto, video, dan dokumen Anda secara otomatis.',
            fastReliable: 'Cepat & Andal',
            fastReliableDesc: 'Unggah dan unduh secepat kilat dengan kinerja server yang andal.',
            serverMonitoring: 'Pemantauan Server',
            serverMonitoringDesc: 'Pantau penggunaan CPU, RAM, penyimpanan, dan jaringan secara real-time.',
            freeOpen: 'Gratis & Terbuka',
            freeOpenDesc: 'Tanpa biaya bulanan. Host di perangkat keras Anda sendiri dan pertahankan kendali penuh.',
        },
        platforms: {
            title: 'Tersedia Di Mana Saja',
            description: 'Akses file Anda dari perangkat apa pun, di mana saja di dunia.',
        },
        cta: {
            title: 'Siap Memulai?',
            description: 'Unduh HomeCloud sekarang dan mulai kelola penyimpanan cloud pribadi Anda secara gratis.',
            button: 'Unduh Sekarang',
        },
        howToUse: {
            title: 'Cara Menggunakan',
            subtitle: 'Panduan lengkap untuk menginstal dan menyambungkan aplikasi HomeCloud dengan server Anda.',
            featuresTitle: '✨ Fitur yang Tersedia',
            featuresDesc: 'HomeCloud hadir dengan berbagai fitur canggih untuk mengelola penyimpanan cloud pribadi Anda.',
            uploadDownload: 'Unggah & Unduh',
            uploadDownloadDesc: 'Unggah file atau folder dari perangkat Anda, dan unduh kapan saja dengan mudah.',
            autoBackup: 'Backup Otomatis',
            autoBackupDesc: 'Backup otomatis foto dan video dari galeri ponsel Anda ke server.',
            fileManager: 'Manajer File',
            fileManagerDesc: 'Kelola file dengan mudah: ganti nama, pindahkan, hapus, dan buat folder baru.',
            mediaPlayer: 'Pemutar Media',
            mediaPlayerDesc: 'Putar video dan musik langsung dari aplikasi dengan streaming dari server.',
            secureAccess: 'Akses Aman',
            secureAccessDesc: 'Akses aman dengan autentikasi pengguna dan enkripsi data.',
            step1: 'LANGKAH 1',
            step2: 'LANGKAH 2',
            step3: 'LANGKAH 3',
            serverSetup: '🖥️ Setup Backend Server',
            serverSetupDesc: 'Server ini adalah pusat penyimpanan data Anda. Instal di PC yang selalu menyala.',
            clientSetup: '📱 Instal Aplikasi Client',
            clientSetupDesc: 'Aplikasi untuk mengakses dan mengelola file Anda dari berbagai perangkat.',
            connectionGuide: '🔗 Menghubungkan App ke Server',
            ensureServerOn: 'Pastikan Server Menyala',
            ensureServerOnDesc: 'Jalankan server backend di komputer Anda dengan perintah',
            findIp: 'Cari Alamat IP Server',
            findIpDescWindows: 'Windows: Buka CMD, ketik',
            findIpDescLinux: 'Linux: Buka Terminal, ketik',
            enterAddress: 'Masukkan Alamat ke Aplikasi',
            enterAddressDesc: 'Format:',
            enterAddressExample: 'Contoh:',
            done: 'Selesai!',
            doneDesc: 'Login dengan akun Anda dan mulai kelola file cloud pribadi Anda.',
            serverRequirements: '📋 Persyaratan Server',
            tips: '💡 Tips Penting',
            tipRemote: 'Akses dari Luar Jaringan',
            tipRemoteDesc: 'Untuk mengakses server dari luar rumah, konfigurasi Port Forwarding di router Anda atau gunakan layanan seperti Ngrok/Tailscale.',
            tipSecurity: 'Keamanan',
            tipSecurityDesc: 'Pastikan password akun Anda kuat dan pertimbangkan untuk mengaktifkan HTTPS jika server diakses secara publik.',
            tipBackup: 'Backup Data',
            tipBackupDesc: 'Selalu buat backup berkala dari data server Anda untuk mencegah kehilangan data.',
            tipAlwaysOn: 'Server Selalu Aktif',
            tipAlwaysOnDesc: 'Gunakan komputer/laptop yang selalu menyala atau gunakan VPS/cloud server untuk ketersediaan 24/7.',
            serverSteps: [
                { title: 'Instal Golang', description: 'Pastikan Go (Golang) sudah terinstal di sistem Anda. Unduh dari go.dev jika belum.' },
                { title: 'Unduh Server', description: 'Unduh source code HomeCloud Server (.zip) dari halaman Unduh.' },
                { title: 'Ekstrak File', description: 'Ekstrak file .zip ke folder pilihan Anda di komputer/server.' },
                { title: 'Jalankan Server', description: 'Buka terminal di folder tersebut dan jalankan: go run main.go. Server akan aktif di port default.' },
            ],
            appSteps: [
                { title: 'Unduh Aplikasi', description: 'Pilih platform Anda (Android/Windows/Linux) dan unduh aplikasinya.' },
                { title: 'Instal Aplikasi', description: 'Instal file APK (Android), EXE (Windows), atau AppImage (Linux).' },
                { title: 'Masukkan Alamat Server', description: 'Buka aplikasi, masukkan IP dan Port server Anda (contoh: http://192.168.1.10:8080).' },
                { title: 'Login & Gunakan', description: 'Login dengan akun Anda dan mulai mengelola file cloud Anda!' },
            ]
        },
        download: {
            title: 'Unduh',
            subtitle: 'Pilih platform Anda dan mulai gunakan penyimpanan cloud pribadi Anda hari ini. Semua unduhan gratis.',
            clientApps: 'Aplikasi Client',
            serverApp: 'Aplikasi Server',
            serverAppDesc: 'Instal ini di PC atau server Anda untuk menghosting penyimpanan cloud Anda.',
            systemReq: 'Persyaratan Sistem',
            mobileApps: 'Aplikasi Mobile',
            desktopServer: 'Desktop & Server',
            comingSoon: 'Segera Hadir',
            openApp: 'Buka Aplikasi',
            download: 'Unduh',
            serverDownload: {
                name: 'Source Code HomeCloud Server',
                desc: 'Backend server source code (Memerlukan Golang)',
            },
            reqMobile: [
                '• Android 7.0 (Nougat) atau lebih baru',
                '• iOS 12.0 atau lebih baru',
                '• Minimal 100 MB penyimpanan kosong',
                '• Koneksi internet'
            ],
            reqServer: [
                '• Windows, Linux, atau macOS',
                '• Go (Golang) 1.18 atau lebih baru terinstal',
                '• Minimal 2 GB RAM',
                '• 500 MB penyimpanan kosong (plus file Anda)',
                '• Akses jaringan untuk koneksi remote'
            ]
        },
        about: {
            title: 'Tentang',
            subtitle: 'HomeCloud adalah solusi penyimpanan cloud mandiri yang memberi Anda kendali penuh atas data Anda.',
            whatIsTitle: 'Apa itu HomeCloud?',
            whatIsDesc1: 'HomeCloud adalah tempat perlindungan data pribadi Anda. Tidak seperti layanan cloud publik, data Anda tetap ada di perangkat Anda sendiri.',
            whatIsDesc2: 'Kami membangun HomeCloud untuk memberi Anda kenyamanan penyimpanan cloud tanpa harus mematuhi kebijakan privasi pihak ketiga.',
            whatIsDesc3: 'Kendali penuh, nol biaya berlangganan, dan potensi penyimpanan tidak terbatas.',
            statsPrivate: 'Pribadi',
            statsFee: 'Biaya',
            statsPlatforms: 'Platform',
            statsStorage: 'Penyimpanan',
            howItWorksTitle: 'Cara Kerja',
            howItWorksDesc: 'Memulai dengan HomeCloud itu sederhana. Siapkan server Anda, hubungkan perangkat Anda, dan mulai sinkronisasi.',
            step1Title: 'Siapkan Server',
            step1Desc: 'Instal backend di PC atau perangkat yang selalu menyala.',
            step2Title: 'Hubungkan App',
            step2Desc: 'Unduh aplikasi klien dan masukkan IP server Anda.',
            step3Title: 'Mulai Sinkronisasi',
            step3Desc: 'Unggah file dan akses dari mana saja.',
            missionTitle: 'Misi Kami',
            missionDesc: 'Menyediakan alternatif penyimpanan cloud yang aman, pribadi, dan mudah digunakan yang menghormati privasi dan kepemilikan data Anda.',
            storyTitle: 'Cerita Kami',
            storyDesc: 'Dimulai sebagai proyek pribadi untuk memecahkan masalah penyimpanan terbatas pada layanan cloud gratis, HomeCloud telah berkembang menjadi platform yang tangguh untuk semua orang.',
            teamTitle: 'Tim',
            teamDesc: 'Dibangun oleh pengembang yang bersemangat yang percaya pada masa depan perangkat lunak terdesentralisasi dan mandiri.',
        }
    }
}

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('id') // Default to Indonesian

    const toggleLanguage = () => {
        setLanguage((prev) => (prev === 'en' ? 'id' : 'en'))
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t: translations[language] }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => useContext(LanguageContext)
